#!/usr/bin/env bash
# multi-model-router setup
# 把 API key 安全写入 ~/.config/api_keys.env
# 用法: bash scripts/setup.sh

set -euo pipefail

ENV_FILE="$HOME/.config/api_keys.env"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROVIDERS_FILE="$SCRIPT_DIR/providers.json"

# 颜色
G='\033[0;32m'  # green
Y='\033[0;33m'  # yellow
R='\033[0;31m'  # red
N='\033[0m'     # reset

echo ""
echo "=========================================="
echo " Multi-Model Router · Setup"
echo "=========================================="
echo ""

# 1. 已存在 → 询问是否覆盖
if [[ -f "$ENV_FILE" ]]; then
  echo -e "${Y}已存在: $ENV_FILE${N}"
  read -r -p "覆盖? [y/N] " yn
  [[ "$yn" =~ ^[Yy]$ ]] || { echo "已取消。"; exit 0; }
fi

# 2. 选服务商(展示预设,允许自定义)
echo ""
echo "选择 API 服务商 (Provider):"
echo ""

if [[ -f "$PROVIDERS_FILE" ]] && command -v jq &>/dev/null; then
  # 列出预设
  mapfile -t PROVIDER_NAMES < <(jq -r 'keys[]' "$PROVIDERS_FILE")
  i=1
  for name in "${PROVIDER_NAMES[@]}"; do
    base=$(jq -r --arg k "$name" '.[$k].base' "$PROVIDERS_FILE")
    desc=$(jq -r --arg k "$name" '.[$k].description // ""' "$PROVIDERS_FILE")
    printf "  %d) %-20s %s\n" "$i" "$name" "$desc"
    printf "     %s\n" "$base"
    i=$((i+1))
  done
  printf "  %d) %-20s %s\n" "$i" "Custom" "手动输入 endpoint"
  echo ""
  read -r -p "选择 [1-$i]: " choice

  if [[ "$choice" -ge 1 && "$choice" -lt "$i" ]]; then
    idx=$((choice-1))
    name="${PROVIDER_NAMES[$idx]}"
    api_base=$(jq -r --arg k "$name" '.[$k].base' "$PROVIDERS_FILE")
    echo -e "${G}已选: $name → $api_base${N}"
  else
    read -r -p "Endpoint URL (例: https://api.example.com/v1): " api_base
  fi
else
  read -r -p "Endpoint URL (例: https://api.example.com/v1): " api_base
fi

# 3. 收 key(隐藏输入,不进 history)
echo ""
echo "粘贴 API Key (输入隐藏,Enter 提交):"
read -r -s api_key
echo ""

# 校验非空
if [[ -z "${api_key// }" || -z "${api_base// }" ]]; then
  echo -e "${R}❌ key 或 base 为空,已取消${N}"
  exit 1
fi

# 4. 写文件,权限 600
mkdir -p "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by multi-model-router setup at $(date '+%Y-%m-%d %H:%M:%S')
# DO NOT commit this file to git
export LLM_API_KEY="$api_key"
export LLM_API_BASE="$api_base"
EOF
chmod 600 "$ENV_FILE"

echo -e "${G}✅ 已写入: $ENV_FILE (权限 600)${N}"
echo ""

# 5. 立即跑 verify.sh
if [[ -x "$SCRIPT_DIR/verify.sh" ]]; then
  echo "运行验证..."
  echo ""
  bash "$SCRIPT_DIR/verify.sh" || {
    echo ""
    echo -e "${Y}⚠️  验证失败。请检查 endpoint 和 key 后重新运行 setup.sh${N}"
    exit 1
  }
else
  echo -e "${Y}提示: 运行 bash scripts/verify.sh 验证安装${N}"
fi
